name: zotero-snap
title: Zotero
base: core20 # the base snap is the execution environment for this snap
version: '6.0'
summary: Zotero helps you collect, organize, cite, and share research.
description: |
  Zotero is a free, easy-to-use tool to help you collect, organize, cite, and
  share research.
icon: snap/local/zotero-icon.png

grade: stable
confinement: strict
architectures: [amd64]

compression: lzo

parts:
  icon:
    plugin: dump
    source: snap/local
  zotero:
    plugin: dump
    source: https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=$SNAPCRAFT_PROJECT_VERSION
    source-type: tar
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      # - libgtk2.0-0

apps:
  zotero-snap:
    extensions: [gnome-3-38]
    command: zotero
    desktop: zotero-launch.desktop
    plugs:
      - network-bind
      - browser-support
      - home
      - removable-media
    environment:
      DISABLE_WAYLAND: 1
      HOME: $SNAP_USER_COMMON
      XDG_CONFIG_HOME: $SNAP_USER_COMMON

